# Generated by Django 5.2.1 on 2025-06-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=8)),
                ('fechaNac', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_almacen', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inhabilitado', 'Inhabilitado')], default='Activo', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('nombreHistoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('imagen_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pasarela',
            fields=[
                ('id_pasarela', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('url_api', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inhabilitado', 'Inhabilitado')], default='Activo', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=100)),
                ('razonSocial', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=20)),
                ('nombreContacto', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inhabilitado', 'Inhabilitado')], default='Activo', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAdministrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WebUDH.usuario')),
                ('tipo_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.tipoadministrador')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fechaComentario', models.DateField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.usuario')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(auto_now=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado')], default='Activo', max_length=40)),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(auto_now=True)),
                ('pasarela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.pasarela')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Historia',
            fields=[
                ('id_postHistoria', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contexto', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.historia')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('talla', models.CharField(max_length=40, null=True)),
                ('stock', models.IntegerField()),
                ('imagen_url', models.CharField(max_length=200)),
                ('id_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.almacen')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.categoria')),
                ('id_promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebUDH.promocion')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.producto')),
            ],
            options={
                'unique_together': {('carrito', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ManyToManyField(through='WebUDH.Carrito_Producto', to='WebUDH.producto'),
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateField(auto_now=True)),
                ('valoracion', models.CharField(max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario',
            field=models.ManyToManyField(through='WebUDH.Reseña', to='WebUDH.usuario'),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_partido', models.CharField(max_length=100)),
                ('lugar_partido', models.CharField(max_length=50)),
                ('fecha_partido', models.DateField()),
                ('hora_partido', models.TimeField()),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.administrador')),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.administrador'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_jugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('posicion', models.CharField(max_length=50)),
                ('dorsal', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nacionalidad', models.CharField(max_length=25)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.administrador')),
            ],
        ),
        migrations.AddField(
            model_name='historia',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.administrador'),
        ),
    ]
