# Generated by Django 5.2.1 on 2025-06-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='id_jugador',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_almacen',
            new_name='almacen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_promocion',
            new_name='promocion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_proveedor',
            new_name='proveedor',
        ),
    ]
